### ISSUE TITLE
Windows (XP i know, it`s old...)...

### ISSUE THREAD

**Issue by wesleycoder** [scripted-editor/scripted#292]
I've been trying to install on xp and node v and i've got this

###error details below:

bower cloning git://github.com/jrburke/requirejs
bower caching git://github.com/jrburke/requirejs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! scripted@0.5.0 postinstall: `cd client && bower install`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the scripted@0.5.0 postinstall script.
npm ERR! This is most likely a problem with the scripted package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls scripted
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\n
pm-cli.js" "install" "-g" "scripted"
npm ERR! cwd C:\Documents and Settings\Administrador
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Documents and Settings\Administrador\npm-debug.log
npm ERR! not ok code 0

C:\Documents and Settings\Administrador>

###npm-debug.log contents below:

14598 verbose about to build C:\Documents and Settings\Administrador\Dados de aplicativos\npm\node_modules\scripted
14599 info build C:\Documents and Settings\Administrador\Dados de aplicativos\npm\node_modules\scripted
14600 verbose linkStuff [ true,
14600 verbose linkStuff   'C:\\Documents and Settings\\Administrador\\Dados de aplicativos\\npm\\node_modules',
14600 verbose linkStuff   true,
14600 verbose linkStuff   'C:\\Documents and Settings\\Administrador\\Dados de aplicativos\\npm\\node_modules' ]
14601 info linkStuff scripted@0.5.0
14602 verbose linkBins scripted@0.5.0
14603 verbose link bins [ { scr: './bin/scr', scripted: './bin/scripted' },
14603 verbose link bins   'C:\\Documents and Settings\\Administrador\\Dados de aplicativos\\npm',
14603 verbose link bins   true ]
14604 verbose linkMans scripted@0.5.0
14605 verbose rebuildBundles scripted@0.5.0
14606 verbose rebuildBundles [ '.bin',
14606 verbose rebuildBundles   'amdefine',
14606 verbose rebuildBundles   'bower',
14606 verbose rebuildBundles   'enhanced-resolve',
14606 verbose rebuildBundles   'express',
14606 verbose rebuildBundles   'formidable',
14606 verbose rebuildBundles   'htmlparser',
14606 verbose rebuildBundles   'json5',
14606 verbose rebuildBundles   'mime',
14606 verbose rebuildBundles   'node-static',
14606 verbose rebuildBundles   'optimist',
14606 verbose rebuildBundles   'priorityqueuejs',
14606 verbose rebuildBundles   'rest',
14606 verbose rebuildBundles   'serv',
14606 verbose rebuildBundles   'sockjs',
14606 verbose rebuildBundles   'websocket-multiplex',
14606 verbose rebuildBundles   'when' ]
14607 info install scripted@0.5.0
14608 info postinstall scripted@0.5.0
14609 verbose unsafe-perm in lifecycle true
14610 info scripted@0.5.0 Failed to exec postinstall script
14611 info C:\Documents and Settings\Administrador\Dados de aplicativos\npm\node_modules\scripted unbuild
14612 info preuninstall scripted@0.5.0
14613 info uninstall scripted@0.5.0
14614 verbose true,C:\Documents and Settings\Administrador\Dados de aplicativos\npm\node_modules,C:\Documents and Settings\Administrador\Dados de aplicativos\npm\node_modules unbuild scripted@0.5.0
14615 verbose C:\Documents and Settings\Administrador\Dados de aplicativos\npm,[object Object] binRoot
14616 info postuninstall scripted@0.5.0
14617 error scripted@0.5.0 postinstall: `cd client && bower install`
14617 error Exit status 8
14618 error Failed at the scripted@0.5.0 postinstall script.
14618 error This is most likely a problem with the scripted package,
14618 error not with npm itself.
14618 error Tell the author that this fails on your system:
14618 error     cd client && bower install
14618 error You can get their info via:
14618 error     npm owner ls scripted
14618 error There is likely additional logging output above.
14619 error System Windows_NT 5.1.2600
14620 error command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "scripted"
14621 error cwd C:\Documents and Settings\Administrador
14622 error node -v v0.10.24
14623 error npm -v 1.3.21
14624 error code ELIFECYCLE
14625 verbose exit [ 1, true ]

**Comment by dwking2000** [comment]
Got same problem with Windows 7 running in the cmd.exe console. Solved it by running GitBash (mingw32) as Admin and then running npm commands.

**Comment by wesleycoder** [comment]
Better not to keep it open, linux solved my problem...
