### ISSUE TITLE
Failed install on OS X El Capitan

### ISSUE THREAD

**Issue by Nickolay-Suslov** [scripted-editor/scripted#304]
> cd client && bower install

bower cloning git://github.com/requirejs/text
bower cloning git://github.com/cujojs/when.git
bower cloning git://github.com/cujojs/wire.git
bower cloning git://github.com/cujojs/curl
bower cloning git://github.com/requirejs/i18n
bower cloning git://github.com/cujojs/rest.git
bower cloning git://github.com/s2js/probes.git
bower cloning git://github.com/aseemk/json5.git
bower cached git://github.com/requirejs/text
bower fetching requirejs-text
bower cloning git://github.com/jrburke/requirejs-bower.git
bower cached git://github.com/cujojs/when.git
bower fetching when
bower caching git://github.com/cujojs/wire.git
bower cached git://github.com/cujojs/curl
bower fetching curl
bower caching git://github.com/requirejs/i18n
bower caching git://github.com/cujojs/rest.git
bower cached git://github.com/s2js/probes.git
bower fetching probes
bower caching git://github.com/aseemk/json5.git
bower cloning git://github.com/cujojs/meld.git
bower error status code of git: 128
child_process.js:332
    throw new TypeError('options argument must be an object');
    ^

TypeError: options argument must be an object
    at normalizeSpawnArguments (child_process.js:332:11)
    at exports.spawn (child_process.js:356:38)
    at module.exports (/Volumes/Macintosh WD/scripted/node_modules/bower/lib/util/spawn.js:17:12)
    at module.exports (/Volumes/Macintosh WD/scripted/node_modules/bower/lib/util/git-cmd.js:19:12)
    at null.<anonymous> (/Volumes/Macintosh WD/scripted/node_modules/bower/lib/core/package.js:611:18)
    at /Volumes/Macintosh WD/scripted/node_modules/mkdirp/index.js:20:20
    at FSReqWrap.oncomplete (fs.js:82:15)

npm WARN EPACKAGEJSON scripted@0.5.0 license should be a valid SPDX license expression
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! scripted@0.5.0 postinstall: `cd client && bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scripted@0.5.0 postinstall script 'cd client && bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scripted package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls scripted
npm ERR! There is likely additional logging output above.

**Comment by aeisenberg** [comment]
Wonder if this is a node version problem. Scripted was originally developed on node 0.8. Can you try installing with a 0.10 version or earlier?
